// DO NOT EDIT. This file is generated by Firebase Studio.
// To regenerate this file, re-run the Firebase initialization command.

import { initializeApp, getApps, getApp } from 'firebase/app';
import { getFirestore } from 'firebase/firestore';

const firebaseConfig = {
  apiKey: "TODO: YOUR_API_KEY",
  authDomain: "TODO: YOUR_AUTH_DOMAIN",
  projectId: "kaitiaki-ara",
  storageBucket: "TODO: YOUR_STORAGE_BUCKET",
  messagingSenderId: "TODO: YOUR_MESSAGING_SENDER_ID",
  appId: "TODO: YOUR_APP_ID"
};

// Initialize Firebase
const app = !getApps().length ? initializeApp(firebaseConfig) : getApp();
const db = getFirestore(app);

export { app, db };
